#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y   	+= himax_platform.o himax_852xES.o

