#ifndef _KD_CAMERA_HW_H_
#define _KD_CAMERA_HW_H_


#include <mach/mt_gpio.h>
#include <mach/mt_pm_ldo.h>
#include "pmic_drv.h"

#if 0
//
//Analog
#define CAMERA_POWER_VCAM_A         PMIC_APP_MAIN_CAMERA_POWER_A
//Digital
#define CAMERA_POWER_VCAM_D         PMIC_APP_MAIN_CAMERA_POWER_D
//AF
#define CAMERA_POWER_VCAM_A2        PMIC_APP_MAIN_CAMERA_POWER_AF
//digital io
#define CAMERA_POWER_VCAM_D2        PMIC_APP_MAIN_CAMERA_POWER_IO
//Digital for Sub
#define SUB_CAMERA_POWER_VCAM_D     PMIC_APP_SUB_CAMERA_POWER_D


//FIXME, should defined in DCT tool
//Main sensor
#define CAMERA_CMRST_PIN            GPIO_CAMERA_CMRST_PIN
#define CAMERA_CMRST_PIN_M_GPIO     GPIO_CAMERA_CMRST_PIN_M_GPIO

#define CAMERA_CMPDN_PIN            GPIO_CAMERA_CMPDN_PIN
#define CAMERA_CMPDN_PIN_M_GPIO     GPIO_CAMERA_CMPDN_PIN_M_GPIO

//FRONT sensor
#define CAMERA_CMRST1_PIN           GPIO_CAMERA_CMRST1_PIN
#define CAMERA_CMRST1_PIN_M_GPIO    GPIO_CAMERA_CMRST1_PIN_M_GPIO

#define CAMERA_CMPDN1_PIN           GPIO_CAMERA_CMPDN1_PIN
#define CAMERA_CMPDN1_PIN_M_GPIO    GPIO_CAMERA_CMPDN1_PIN_M_GPIO


//Main2 sensor
#define CAMERA_CMRST2_PIN           GPIO_CAMERA_CMRST_PIN
#define CAMERA_CMRST2_PIN_M_GPIO    GPIO_CAMERA_CMRST_PIN_M_GPIO

#define CAMERA_CMPDN2_PIN           GPIO_CAMERA_CMPDN_PIN
#define CAMERA_CMPDN2_PIN_M_GPIO    GPIO_CAMERA_CMPDN_PIN_M_GPIO
#endif

/*MM-SL-ModifyForDP-00*{ */
/*MM-SL-BringUpIMX230-00+{*/
/*MM-SL-BringUpIMX214-00+{*/
//GPIO 
#ifndef GPIO_CAMERA_CMPDN_PIN
#define GPIO_CAMERA_CMPDN_PIN GPIO10
#endif

#ifndef GPIO_CAMERA_CMRST_PIN
#define GPIO_CAMERA_CMRST_PIN GPIO41
#endif

#ifndef GPIO_CAMERA_CMRST1_PIN
#define GPIO_CAMERA_CMRST1_PIN GPIO14
#endif

#ifndef GPIO_CAMERA_CMMCLK_EN_PIN 
#define GPIO_CAMERA_CMMCLK_EN_PIN GPIO42
#endif

#ifndef GPIO_CAMERA_CM2MCLK_EN_PIN 
#define GPIO_CAMERA_CM2MCLK_EN_PIN GPIO39
#endif

//Power 
//Analog
#define CAMERA_POWER_VCAM_A MT6331_POWER_LDO_VCAMA
#define CAMERA_POWER_VSRAM  MT6331_POWER_LDO_VSRAM_DVFS1

//Digital
#define CAMERA_POWER_VCAM_D MT6331_POWER_LDO_VCAMD
#define CAMERA_POWER_VGP1   MT6331_POWER_LDO_VGP1

//AF
#define CAMERA_POWER_VCAM_A2 MT6331_POWER_LDO_VCAM_AF
//digital io
#define CAMERA_POWER_VCAM_D2 MT6331_POWER_LDO_VCAM_IO

/*MM-SL-BringUpIMX214-00+} */
/*MM-SL-BringUpIMX230-00+}*/
/*MM-SL-ModifyForDP-00*} */

// Define I2C Bus Num
#define SUPPORT_I2C_BUS_NUM1        0
#define SUPPORT_I2C_BUS_NUM2        2
#endif
