include $(srctree)/drivers/misc/mediatek/Makefile.custom
# HEADER FILE
ccflags-y += -I$(srctree)/drivers/misc/mediatek/devinfo/$(subst ",,$(CONFIG_MTK_PLATFORM))
obj-y += devinfo.o
obj-y += devinfosys.o
obj-y += fih_proc_fs.o
obj-y += fih_board_info_init.o
